# Generated by Django 5.1.2 on 2024-11-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tagmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagManager',
        ),
    ]
